print("Welcome to the Tip Calculator")
total_bill = float(input("What was your total bill?"))
tip_amount = int(input("How much tip would you like to give? 10,12 or 15"))
people = int(input("How many people to split the bill?"))
tip_calculator = round(((total_bill+(total_bill*tip_amount/100))/people),2)
print (f"Each person should pay: ${tip_calculator}")